version: '2'
services:
  oders-ms:
      #Image
      image: localhost:3000/orders-ms:0.1.0
      #Uncomment if you wish to build from source code
      build: .
      depends_on:
        - orders-mongo-db
      ports:
        - "3000:3000"
      command: npm start
      links:
        - orders-mongo-db

  orders-mongo-db:
      image: mongo:3.2.9
