version: '2'
services:
  product-subscriber:
      #Image
      #image: localhost/product-sub-ms:0.1.1
      image: luisw19/product-sub-ms:0.1.1
      #Uncomment "build" if you wish to build from source code, otherwise it'll pull from registry
      build: ./product-subscriber-ms
      environment:
        KAFKA_BROKER: '129.150.77.116:6667'
        KAFKA_REGISTRY: 'http://129.150.114.134:8081'
        ORDERSAPI_HOST: 'oders-ms'
        ORDERSAPI_PORT: 3000
      command: node product-subscriber-ms.js
      links:
        - oders-ms

  oders-ms:
      #Image
      #image: localhost:3000/orders-ms:0.1.0
      image: luisw19/orders-ms:0.1.0
      #Uncomment "build" if you wish to build from source code, otherwise it'll pull from registry
      build: .
      depends_on:
        - orders-mongo-db
      ports:
        - "3000:3000"
      command: npm start
      links:
        - orders-mongo-db

  orders-mongo-db:
      image: mongo:3.2.9
