version: '2'
services:
  oders-ms:
      #Uncomment if you wish to build from source code
      build: .
      #Uncomment if you wish to run from docker-hub image
      #image: luisw19/orders-ms
      depends_on:
        - mongo_db
      ports:
        - "3000:3000"
      command: npm start
      links:
        - mongo_db

  mongo_db:
      image: mongo:3.2.9
