# APP DEPLOYMENT

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    run: orders-ms
  name: orders-ms
spec:
  replicas: 1
  selector:
    matchLabels:
      run: orders-ms-exposed
  template:
    metadata:
      labels:
        run: orders-ms-exposed
    spec:
      #containers:
      #- image: localhost:3000/orders-ms:0.1.0
      #- image: luisw19/orders-ms:1.0.0
      #  name: orders-ms
      #  ports:
      #  - containerPort: 3000
      #    hostPort: 3000
      #    protocol: TCP
      containers:
      - args:
        - npm
        - start
        env:
        - name: EVENTAPI_HOST
          #name of service in orders-prod-ms manifest
          value: orders-prod-ms
        - name: EVENTAPI_PORT
          value: 4000
        #image: localhost:3000/orders-prod-ms:0.1.1
        image: luisw19/orders-ms:1.0.0
        name: orders-ms
      restartPolicy: Always

---

# APP SERVICE

apiVersion: v1
kind: Service
metadata:
  labels:
    run: orders-ms
  name: orders-ms
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    run: orders-ms-exposed
  type: NodePort
